name: Test Suite

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Install dependencies
        run: go mod download
      
      - name: Run unit tests
        run: go test -v -race ./server/... ./types/... ./messaging/... -coverprofile=coverage.txt
      
      - name: Check race conditions
        run: go test -race -count=10 ./server/... -run Race
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: Build React app
        working-directory: web
        run: |
          npm ci
          npm run build
      
      - name: Build Go server
        run: go build -o poker
      
      - name: Install E2E dependencies
        working-directory: e2e
        run: |
          npm ci
          npx playwright install --with-deps chromium
      
      - name: Start server in background
        run: ./poker server &
        
      - name: Wait for server
        run: npx wait-on http://localhost:9867 --timeout 30000
      
      - name: Run E2E tests
        working-directory: e2e
        run: npm test
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30

